version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing Trivy & SonarQube scanner..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-* sonar-scanner
      - export PATH=$PATH:$PWD/sonar-scanner/bin

  pre_build:
    commands:
      - echo "Running Trivy file system scan..."
      - ./trivy fs . || true

      - echo "Running SonarQube analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=swiggy \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://http://13.201.12.34:9000 \
          -Dsonar.login=$SONAR_TOKEN

  build:
    commands:
      - echo "Logging in to DockerHub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest" .

      - echo "Pushing Docker image to DockerHub..."
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"swiggy","imageUri":"%s/%s/swiggy:latest"}]' $DOCKER_REGISTRY_URL $DOCKER_REGISTRY_USERNAME > imagedefinitions.json

      - echo "Sending build result email via AWS SES..."
      - |
        aws ses send-email \
          --from "svs240395@gmail.com" \
          --destination '{"ToAddresses":["svs240395@gmail.com"]}' \
          --message '{"Subject":{"Data":"CodeBuild Status: '$CODEBUILD_BUILD_ID'"},"Body":{"Text":{"Data":"Build status: '$CODEBUILD_BUILD_STATUS'"}}}' \
          --region "ap-south-1"

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json

